name: prev_hosp_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pyarrow
  - python-duckdb
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - altair
    - ipykernel
